version: '3'
services:
  ollama:
    image: ollama/ollama
    volumes:
      - data_volume:/root/.ollama
    ports:
      - 11434:11434

  chromadb:
    image: chromadb/chroma
    volumes:
      - data_volume:/chroma/.chroma
    ports:
      - 8000:8000

volumes:
  data_volume:
    driver: local
